
#include "StandardKeyboardEvents.h"

#include "../Lua/LuaEnvironment.h"

namespace PE {
namespace Events {

	PE_IMPLEMENT_CLASS1(Event_KEY_A_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_A_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_A_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_S_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_D_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_D_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_D_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_W_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_PERIOD_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_COMMA_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_K_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_K_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_K_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_L_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_L_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_L_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_LEFT_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_LEFT_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_LEFT_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_DOWN_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_RIGHT_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_RIGHT_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_RIGHT_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_UP_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_P_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_P_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_P_UP, Event);

};
};
